### ISSUE TITLE
Some interactive content doesn't print

### ISSUE THREAD

**Issue by drzax** [abcnews/remove-fallback-content#2]
We had some feedback that chart of the day stories weren't printing properly. It looks like datawrapper doesn't print at all well, and I suspect it's similar for most interactive content, so maybe it's better to deal with print fallbacks here too.

Maybe we could retain the non-interactive elements for a print stylesheet?

**Comment by colingourlay** [comment]
I like this idea a lot. I'm going in...

**Comment by colingourlay** [comment]
See #883017d91a43d9a13b23bc10b3b70c097c7c8ddf

**Comment by colingourlay** [comment]
Also worth discussing: do we want to replicate this behaviour in Odyssey?

**Comment by drzax** [comment]
I think it might be. 

(p.s. while you're there, @colingourlay — could you take a peek at the security alerts on this repo?)

**Comment by colingourlay** [comment]
All sorted by updating dependencies 🎉
