### ISSUE TITLE
Possible confusion with Stash version

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/remove-fallback-content#4]
Does this fully replace https://stash.abc-dev.net.au/projects/NEWS/repos/remove-fallback-content/browse ?

Is it OK to delete that repository?

CC @andrewkesper

**Comment by andrewkesper** [comment]
They seem to do a very similar job. The major difference is that this version looks for #remove and #endremove and the stash version looks for #fallback and #endfallback. It's unfortunate they both share the same repo name. 

I guess the best option would be to delete one of them and make sure the one that stays can support both tag names?

**Comment by drzax** [comment]
If there are no other major differences, can I suggest we consolidate into this repo by either adding the `#fallback` option here, or simply deprecating the other one?

Looks like we've all had this idea at some point. This repo was spawned out of a DSI copy of Odyssey functionality so it would be available outside Odyssey.

**Comment by blakebutcher** [comment]
I could only find 3 articles containing "endfallback" (vs 284 containing "endremove") so they could be updated to use the #remove/#endremove solution.

Everyone happy if I delete https://stash.abc-dev.net.au/projects/NEWS/repos/remove-fallback-content/browse and update those 3 articles?

**Comment by andrewkesper** [comment]
> I could only find 3 articles containing "endfallback" (vs 284 containing "endremove") so they could be updated to use the #remove/#endremove solution.
> 
> Everyone happy if I delete https://stash.abc-dev.net.au/projects/NEWS/repos/remove-fallback-content/browse and update those 3 articles?

Yep. That sounds like the best approach. (I didn't realise #remove/#endremove was so heavily used.)

**Comment by blakebutcher** [comment]
I've deleted the Stash repo.

The 3 published articles that contain "endfallback" are:

https://www.abc.net.au/news/2018-09-12/australias-worst-car-commutes-explored/9944484
I've bumped this to use remove-fallback-content 2.0.0 (from 1.0.1) and updated it to use #remove/#endremove in the text

https://www.abc.net.au/news/2018-08-16/when-will-scott-morrison-call-the-election/10012820
The fallback JS is built into https://www.abc.net.au/res/sites/news-projects/elections-federal2019-date-speculation-game/3.0.0/index.js - @andrewkesper can you please sort this one out?

https://www.abc.net.au/news/2019-02-07/election-labor-coalition-liberal-policies-show-me-the-money/10442114
The fallback JS is built into https://www.abc.net.au/res/sites/news-projects/elections-federal2019-war-chest/1.1.1/index.js - @andrewkesper can you please sort this one out too?

**Comment by andrewkesper** [comment]
I've updated the Election Date story. 

I've left the War Chest story as-is, because the fallback code works differently in this story. Migrating the story to the new system will break the story.
